title: Felipe Carlone Lucio
#logo: /assets/img/headshot_circle.png
description: |
  Felipe Carlone Lucio
  Cientista de Dados | Engenheiro de Produção
  São Paulo/SP – Brasil
  (11) 99313-4960  
#show_downloads: true
theme: jekyll-theme-minimal